"""Runtime JS helpers for dynamic analysis overlays (vectors/main-arrow/coverage)."""


def build_replace_dynamic_vectors_js() -> str:
    """Return JS that replaces vector + main-arrow overlays in-place."""
    return (
        "window.__replaceDynamicVectors = function(payload){"
        "try{"
        "if(!window.L) return;"
        "var m = (typeof findMap === 'function') ? findMap() : null;"
        "if(!m) return;"
        "if(!window.__dynVectors){ window.__dynVectors = {vectors:null, main:null}; }"
        "if(window.__dynVectors.vectors){ try{ m.removeLayer(window.__dynVectors.vectors); }catch(err){} }"
        "if(window.__dynVectors.main){ try{ m.removeLayer(window.__dynVectors.main); }catch(err){} }"
        "if(m && m.eachLayer){"
        "m.eachLayer(function(layer){"
        "try{"
        "if(!layer) return;"
        "var optCls = String((layer.options && layer.options.className) || '');"
        "var pathCls = '';"
        "try{ pathCls = String((layer._path && layer._path.getAttribute) ? (layer._path.getAttribute('class') || '') : ''); }catch(err){}"
        "var cls = (optCls + ' ' + pathCls).trim();"
        "if(!cls) return;"
        "if(cls.indexOf('overlay-vectors') !== -1 || cls.indexOf('overlay-main-arrow') !== -1 || cls.indexOf('dynamic-vectors') !== -1 || cls.indexOf('dynamic-main-arrow') !== -1){"
        "m.removeLayer(layer);"
        "}"
        "}catch(err){}"
        "});"
        "}"
        "window.__dynVectors.vectors = L.layerGroup();"
        "window.__dynVectors.main = L.layerGroup();"
        "var lines = (payload && payload.vectors) ? payload.vectors : [];"
        "lines.forEach(function(l){"
        "try{"
        "L.polyline(l.latlngs || [], {"
        "color:String(l.color||'#fbbf24'), weight:Number(l.weight||2), opacity:Number(l.opacity||0.85),"
        "className:'overlay-vectors dynamic-vectors'"
        "}).addTo(window.__dynVectors.vectors);"
        "}catch(err){}"
        "});"
        "var main = (payload && payload.main_arrow) ? payload.main_arrow : [];"
        "main.forEach(function(l){"
        "try{"
        "L.polyline(l.latlngs || [], {"
        "color:String(l.color||'#60a5fa'), weight:Number(l.weight||4), opacity:Number(l.opacity||0.95),"
        "className:'overlay-main-arrow dynamic-main-arrow'"
        "}).addTo(window.__dynVectors.main);"
        "}catch(err){}"
        "});"
        "window.__dynVectors.vectors.addTo(m);"
        "window.__dynVectors.main.addTo(m);"
        "if(window.__lastOverlayState && window.__applyOverlayVisibility){ window.__applyOverlayVisibility(window.__lastOverlayState); }"
        "}catch(err){}"
        "};"
    )


def build_replace_dynamic_coverage_js() -> str:
    """Return JS that replaces coverage overlay in-place."""
    return (
        "window.__replaceDynamicCoverage = function(payload){"
        "try{"
        "if(!window.L) return;"
        "var m = (typeof findMap === 'function') ? findMap() : null;"
        "if(!m) return;"
        "if(window.__dynCoverage){ try{ m.removeLayer(window.__dynCoverage); }catch(err){} }"
        "if(m && m.eachLayer){"
        "m.eachLayer(function(layer){"
        "try{"
        "if(!layer) return;"
        "var optCls = String((layer.options && layer.options.className) || '');"
        "var pathCls = '';"
        "try{ pathCls = String((layer._path && layer._path.getAttribute) ? (layer._path.getAttribute('class') || '') : ''); }catch(err){}"
        "var cls = (optCls + ' ' + pathCls).trim();"
        "if(!cls) return;"
        "if(cls.indexOf('overlay-coverage') !== -1 || cls.indexOf('dynamic-coverage') !== -1){"
        "m.removeLayer(layer);"
        "}"
        "}catch(err){}"
        "});"
        "}"
        "window.__dynCoverage = L.layerGroup();"
        "var pts = (payload && payload.points) ? payload.points : [];"
        "pts.forEach(function(p){"
        "try{"
        "L.circleMarker([Number(p.lat), Number(p.lon)], {"
        "radius:Number(p.radius||6), color:String(p.color||'#4ade80'), weight:Number(p.weight||1), opacity:0.9,"
        "fill:true, fillColor:String(p.color||'#4ade80'), fillOpacity:Number(p.fill_opacity||0.35),"
        "className:'overlay-coverage dynamic-coverage'"
        "}).addTo(window.__dynCoverage);"
        "}catch(err){}"
        "});"
        "window.__dynCoverage.addTo(m);"
        "if(window.__lastOverlayState && window.__applyOverlayVisibility){ window.__applyOverlayVisibility(window.__lastOverlayState); }"
        "}catch(err){}"
        "};"
    )

