"""Contour runtime JS helpers for MapWidget."""

import json


def build_set_contour_layers_visible_js() -> str:
    """Return JS that hard-toggles contour layers by class on the Leaflet map."""
    return (
        "window.__setContourLayersVisible = function(visible){"
        "try{"
        "var m = (typeof findMap === 'function') ? findMap() : null;"
        "if(!m || !m.eachLayer) return;"
        "m.eachLayer(function(layer){"
        "try{"
        "var optCls = String((layer && layer.options && layer.options.className) || '');"
        "var pathCls = String((layer && layer._path && layer._path.getAttribute) ? (layer._path.getAttribute('class') || '') : '');"
        "var cls = (optCls + ' ' + pathCls).trim();"
        "if(!cls) return;"
        "var isContour = (cls.indexOf('overlay-contours') !== -1) || (cls.indexOf('overlay-contours-fill') !== -1) || (cls.indexOf('contour-line-label') !== -1);"
        "if(!isContour) return;"
        "if(layer._path && layer._path.style){"
        "layer._path.style.display = visible ? '' : 'none';"
        "}"
        "if(layer._icon && layer._icon.style){"
        "layer._icon.style.display = visible ? '' : 'none';"
        "}"
        "}catch(err){}"
        "});"
        "}catch(err){}"
        "};"
    )


def build_replace_dynamic_contours_js(*, contour_color: str) -> str:
    """Return JS that replaces dynamic contour layers and purges stale ones."""
    contour_color_js = json.dumps(str(contour_color).lower())
    return (
        "window.__replaceDynamicContours = function(payload){"
        "try{"
        "if(!window.L) return;"
        "var m = (typeof findMap === 'function') ? findMap() : null;"
        "if(!m) return;"
        f"var contourColor = {contour_color_js};"
        "if(!window.__dynContour){ window.__dynContour = {fill:null,line:null,label:null}; }"
        "if(window.__dynContour.fill){ try{ m.removeLayer(window.__dynContour.fill); }catch(err){} }"
        "if(window.__dynContour.line){ try{ m.removeLayer(window.__dynContour.line); }catch(err){} }"
        "if(window.__dynContour.label){ try{ m.removeLayer(window.__dynContour.label); }catch(err){} }"
        "if(m && m.eachLayer){"
        "m.eachLayer(function(layer){"
        "try{"
        "if(!layer) return;"
        "var opt = layer.options || {};"
        "var optCls = String(opt.className || '');"
        "var pathCls = '';"
        "var iconCls = '';"
        "try{ pathCls = String((layer._path && layer._path.getAttribute) ? (layer._path.getAttribute('class') || '') : ''); }catch(err){}"
        "try{ iconCls = String((layer._icon && layer._icon.getAttribute) ? (layer._icon.getAttribute('class') || '') : ''); }catch(err){}"
        "var cls = (optCls + ' ' + pathCls + ' ' + iconCls).trim();"
        "var remove = false;"
        "if(cls.indexOf('overlay-contours') !== -1 || cls.indexOf('overlay-contours-fill') !== -1 || cls.indexOf('contour-line-label') !== -1 || cls.indexOf('dynamic-contour') !== -1){"
        "remove = true;"
        "} else if(typeof layer.getLatLngs === 'function'){"
        "var c = String(opt.color || '').toLowerCase();"
        "var fc = String(opt.fillColor || '').toLowerCase();"
        "if(c === contourColor || fc === contourColor){"
        "remove = true;"
        "}"
        "if(!remove && opt && opt.fill === true && opt.stroke === false){"
        "remove = true;"
        "}"
        "if(!remove && opt && opt.fill === true && typeof layer.setStyle === 'function' && typeof layer.setRadius !== 'function'){"
        "remove = true;"
        "}"
        "}"
        "if(remove){ m.removeLayer(layer); }"
        "}catch(err){}"
        "});"
        "}"
        "window.__dynContour.fill = L.layerGroup();"
        "window.__dynContour.line = L.layerGroup();"
        "window.__dynContour.label = L.layerGroup();"
        "document.querySelectorAll('.overlay-contours:not(.dynamic-contour)').forEach(function(el){ el.style.display='none'; });"
        "document.querySelectorAll('.overlay-contours-fill:not(.dynamic-contour-fill)').forEach(function(el){ el.style.display='none'; });"
        "document.querySelectorAll('.contour-line-label:not(.dynamic-contour-label)').forEach(function(el){ el.style.display='none'; });"
        "var fills = (payload && payload.fills) ? payload.fills : [];"
        "fills.forEach(function(f){"
        "try{"
        "L.polygon(f.latlngs || [], {"
        "stroke:false, fill:true, fillColor:String(f.color||'#60a5fa'), fillOpacity:Number(f.opacity||0.2),"
        "className:'overlay-contours-fill dynamic-contour-fill'"
        "}).addTo(window.__dynContour.fill);"
        "}catch(err){}"
        "});"
        "var lines = (payload && payload.lines) ? payload.lines : [];"
        "lines.forEach(function(l){"
        "try{"
        "L.polyline(l.latlngs || [], {"
        "color:String(l.color||'#a78bfa'), weight:Number(l.weight||1.0), opacity:Number(l.opacity||0.8),"
        "className:'overlay-contours dynamic-contour contour-level-' + String(l.level_index||0)"
        "}).addTo(window.__dynContour.line);"
        "}catch(err){}"
        "});"
        "var labels = (payload && payload.labels) ? payload.labels : [];"
        "labels.forEach(function(lb){"
        "try{"
        "var txt = String(lb.text||'');"
        "var angle = Number(lb.angle||0);"
        "var fs = Number(lb.font_size||12);"
        "var levelValue = (lb.level_value===undefined||lb.level_value===null)?'':String(lb.level_value);"
        "var hidden = (!!lb.hidden) ? 'display:none;' : '';"
        "var html = '<div style=\"' + hidden + 'font-size:' + fs + 'px;font-weight:500;color:#5a5a5a;text-shadow:0 1px 0 rgba(255,255,255,0.85),0 0 3px rgba(255,255,255,0.65);transform:rotate(' + angle.toFixed(1) + 'deg);white-space:nowrap;\" data-level=\"' + levelValue + '\">' + txt + '</div>';"
        "L.marker([Number(lb.lat), Number(lb.lon)], {"
        "icon: L.divIcon({"
        "className:'contour-line-label dynamic-contour-label contour-level-label-' + String(lb.level_index||0),"
        "html: html, iconSize:[40,14], iconAnchor:[20,7]"
        "})"
        "}).addTo(window.__dynContour.label);"
        "}catch(err){}"
        "});"
        "window.__dynContour.fill.addTo(m);"
        "window.__dynContour.line.addTo(m);"
        "window.__dynContour.label.addTo(m);"
        "if(window.__lastOverlayState && window.__applyOverlayVisibility){ window.__applyOverlayVisibility(window.__lastOverlayState); }"
        "}catch(err){}"
        "};"
    )
