"""External-layer manager/runtime JS helpers for MapWidget."""


def build_external_layers_runtime_js() -> str:
    """Return JS contract for external-layer dialog, list, and style sync."""
    return (
        "window.__externalLayerCatalog = Array.isArray(window.__externalLayerCatalog) ? window.__externalLayerCatalog : [];"
        "window.__selectedExternalLayerId = window.__selectedExternalLayerId || null;"
        "window.__externalLayerStyleTimers = window.__externalLayerStyleTimers || {};"
        "window.__externalLayerOrderSig = window.__externalLayerOrderSig || '';"
        "window.__externalLayerPopupBindSig = window.__externalLayerPopupBindSig || '';"
        "window.__extStyleDefaults = {color:'#22c55e',line_width:2,line_opacity:0.9,fill_opacity:0.12,point_size:8};"
        "window.__extSafeLayerClass = function(layerId){"
        "var raw=String(layerId||'layer').toLowerCase();"
        "raw=raw.replace(/[^a-z0-9_-]+/g,'-').replace(/^-+|-+$/g,'');"
        "if(!raw) raw='layer';"
        "return 'overlay-external-layer-' + raw;"
        "};"
        "window.__extNormalizeStyle = function(style){"
        "style=(style&&typeof style==='object')?style:{};"
        "var d=window.__extStyleDefaults||{};"
        "var color=String(style.color||d.color||'#22c55e');"
        "var lw=Number(style.line_width); if(!isFinite(lw)) lw=Number(style.weight);"
        "if(!isFinite(lw)) lw=Number(d.line_width||2); lw=Math.max(1, Math.min(8, lw));"
        "var lo=Number(style.line_opacity); if(!isFinite(lo)) lo=Number(style.opacity);"
        "if(!isFinite(lo)) lo=Number(d.line_opacity||0.9); lo=Math.max(0.05, Math.min(1, lo));"
        "var fo=Number(style.fill_opacity); if(!isFinite(fo)) fo=Number(style.fillOpacity);"
        "if(!isFinite(fo)) fo=Number(d.fill_opacity||0.12); fo=Math.max(0, Math.min(1, fo));"
        "var ps=Number(style.point_size); if(!isFinite(ps)) ps=Number(style.radius);"
        "if(!isFinite(ps)) ps=Number(d.point_size||8); ps=Math.max(2, Math.min(24, ps));"
        "return {color:color,line_width:lw,line_opacity:lo,fill_opacity:fo,point_size:ps};"
        "};"
        "window.__extHexToRgba = function(hex, alpha){"
        "try{"
        "var a=Number(alpha); if(!isFinite(a)) a=1; a=Math.max(0, Math.min(1, a));"
        "var h=String(hex||'').trim();"
        "var m=h.match(/^#?([0-9a-f]{3}|[0-9a-f]{6})$/i);"
        "if(!m) return 'rgba(34,197,94,' + String(a) + ')';"
        "h=m[1];"
        "if(h.length===3){ h = h[0]+h[0]+h[1]+h[1]+h[2]+h[2]; }"
        "var r=parseInt(h.slice(0,2),16);"
        "var g=parseInt(h.slice(2,4),16);"
        "var b=parseInt(h.slice(4,6),16);"
        "return 'rgba(' + String(r) + ',' + String(g) + ',' + String(b) + ',' + String(a) + ')';"
        "}catch(err){"
        "return 'rgba(34,197,94,0.4)';"
        "}"
        "};"
        "window.__extEscapeHtml = function(value){"
        "var s=String((value===undefined||value===null)?'':value);"
        "return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;').replace(/'/g,'&#39;');"
        "};"
        "window.__extGeometryKind = function(layer){"
        "if(!layer) return 'other';"
        "var g=String(layer.geometry_kind||layer.geometry||'').toLowerCase();"
        "if(g.indexOf('polygon')!==-1) return 'polygon';"
        "if(g.indexOf('line')!==-1) return 'line';"
        "if(g.indexOf('point')!==-1) return 'point';"
        "if(g==='mixed') return 'mixed';"
        "return 'other';"
        "};"
        "window.__getSelectedExternalLayer = function(){"
        "var id=String(window.__selectedExternalLayerId||'');"
        "var list=Array.isArray(window.__externalLayerCatalog)?window.__externalLayerCatalog:[];"
        "for(var i=0;i<list.length;i++){"
        "if(String(list[i].id||'')===id) return list[i];"
        "}"
        "return null;"
        "};"
        "window.__applyExternalLayerZOrder = function(orderIds){"
        "try{"
        "var ids=Array.isArray(orderIds)?orderIds:(Array.isArray(window.__externalLayerCatalog)?window.__externalLayerCatalog.map(function(l){return String(l.id||'');}):[]);"
        "if(!ids.length) return;"
        "var mm=null;"
        "try{ if(window.findMap) mm=window.findMap(); }catch(err){}"
        "try{ if(!mm && window.map && typeof window.map.eachLayer==='function') mm=window.map; }catch(err){}"
        "if(!mm || typeof mm.eachLayer!=='function') return;"
        "ids.forEach(function(layerId){"
        "var need=window.__extSafeLayerClass(layerId);"
        "mm.eachLayer(function(layer){"
        "try{"
        "if(!layer || typeof layer.bringToFront!=='function') return;"
        "var cls='';"
        "if(layer.options && layer.options.className) cls=String(layer.options.className||'');"
        "if((!cls || cls.indexOf(need)===-1) && layer._path && layer._path.getAttribute) cls=String(layer._path.getAttribute('class')||'');"
        "if(String(cls).indexOf(need)===-1) return;"
        "layer.bringToFront();"
        "}catch(err){}"
        "});"
        "});"
        "}catch(err){}"
        "};"
        "window.__openExternalLayerPopup = function(e, layerId){"
        "try{"
        "var mm=null;"
        "try{ if(window.findMap) mm=window.findMap(); }catch(err){}"
        "try{ if(!mm && window.map && typeof window.map.openPopup==='function') mm=window.map; }catch(err){}"
        "if(!mm || !window.L || !window.L.popup) return;"
        "var id=String(layerId||'');"
        "var layerObj=null;"
        "var list=Array.isArray(window.__externalLayerCatalog)?window.__externalLayerCatalog:[];"
        "for(var i=0;i<list.length;i++){ if(String(list[i].id||'')===id){ layerObj=list[i]; break; } }"
        "var name=(layerObj && layerObj.name) ? String(layerObj.name) : 'External Layer';"
        "var kind=(layerObj ? window.__extGeometryKind(layerObj) : 'other');"
        "var props=null;"
        "try{ if(e && e.target && e.target.feature && e.target.feature.properties) props=e.target.feature.properties; }catch(err){}"
        "var latlng=null;"
        "try{ if(e && e.latlng) latlng=e.latlng; }catch(err){}"
        "try{ if(!latlng && e && e.target && typeof e.target.getLatLng==='function') latlng=e.target.getLatLng(); }catch(err){}"
        "if(!latlng) return;"
        "var html='<div class=\\'ha-ext-popup\\'>';"
        "html += '<div class=\\'ha-ext-popup-title\\'>' + window.__extEscapeHtml(name) + '</div>';"
        "var keys=[];"
        "if(props && typeof props==='object'){"
        "try{ keys=Object.keys(props); }catch(err){ keys=[]; }"
        "}"
        "if(keys && keys.length){"
        "keys.sort();"
        "keys=keys.slice(0, 14);"
        "html += '<table class=\\'ha-ext-popup-table\\'>';"
        "for(var k=0;k<keys.length;k++){"
        "var key=keys[k];"
        "var val='';"
        "try{ val=props[key]; }catch(err){ val=''; }"
        "html += '<tr><td class=\\'key\\'>' + window.__extEscapeHtml(key) + '</td><td class=\\'val\\'>' + window.__extEscapeHtml(val) + '</td></tr>';"
        "}"
        "html += '</table>';"
        "}else{"
        "html += '<div style=\\'opacity:0.75; font-size:11px;\\'>(' + window.__extEscapeHtml(kind) + ')</div>';"
        "}"
        "html += '</div>';"
        "window.L.popup({maxWidth: 360, autoPanPadding: [18,18]})"
        ".setLatLng(latlng)"
        ".setContent(html)"
        ".openOn(mm);"
        "}catch(err){}"
        "};"
        "window.__bindExternalLayerPopups = function(){"
        "try{"
        "var mm=null;"
        "try{ if(window.findMap) mm=window.findMap(); }catch(err){}"
        "try{ if(!mm && window.map && typeof window.map.eachLayer==='function') mm=window.map; }catch(err){}"
        "if(!mm || typeof mm.eachLayer!=='function') return;"
        "var list=Array.isArray(window.__externalLayerCatalog)?window.__externalLayerCatalog:[];"
        "if(!list.length) return;"
        "var ids=list.map(function(l){ return String(l.id||''); }).filter(function(v){ return !!v; });"
        "var mid='';"
        "try{ if(mm && mm._leaflet_id!==undefined && mm._leaflet_id!==null) mid=String(mm._leaflet_id); }catch(err){ mid=''; }"
        "var sig=mid + '|' + ids.join('|');"
        "if(sig && String(window.__externalLayerPopupBindSig||'')===sig) return;"
        "var seen=0;"
        "mm.eachLayer(function(layer){"
        "try{"
        "if(!layer) return;"
        "if(typeof layer.on!=='function') return;"
        "var cls='';"
        "if(layer.options && layer.options.className) cls=String(layer.options.className||'');"
        "if((!cls || cls.indexOf('overlay-external-layer-')===-1) && layer._path && layer._path.getAttribute) cls=String(layer._path.getAttribute('class')||'');"
        "if(String(cls).indexOf('overlay-external-layer-')===-1) return;"
        "var matched=null;"
        "for(var i=0;i<ids.length;i++){"
        "var need=window.__extSafeLayerClass(ids[i]);"
        "if(String(cls).indexOf(need)!==-1){ matched=ids[i]; break; }"
        "}"
        "if(!matched) return;"
        "seen += 1;"
        "if(layer.__haExtPopupBound) return;"
        "layer.__haExtPopupBound = true;"
        "(function(layerId){"
        "layer.on('click', function(e){"
        "try{ if(e && e.originalEvent && window.L && window.L.DomEvent) window.L.DomEvent.stop(e.originalEvent); }catch(err){}"
        "window.__openExternalLayerPopup(e, layerId);"
        "});"
        "})(matched);"
        "}catch(err){}"
        "});"
        "if(seen>0) window.__externalLayerPopupBindSig = sig;"
        "}catch(err){}"
        "};"
        "window.toggleExternalLayerDialog = function(forceOpen){"
        "var backdrop=document.getElementById('layerManagerBackdrop');"
        "if(!backdrop) return;"
        "var isOpen=backdrop.classList.contains('open');"
        "var next=(forceOpen===true)?true:((forceOpen===false)?false:!isOpen);"
        "backdrop.classList.toggle('open', next);"
        "if(document && document.body){"
        "document.body.classList.toggle('external-layer-dialog-open', next);"
        "}"
        "if(next){"
        "if(window.__renderExternalLayerList) window.__renderExternalLayerList();"
        "if(window.__syncExternalLayerDetail) window.__syncExternalLayerDetail();"
        "if(window.__updateExternalLayerSummary) window.__updateExternalLayerSummary();"
        "}"
        "};"
        "window.onExternalLayerManagerBackdropClick = function(event){"
        "var backdrop=document.getElementById('layerManagerBackdrop');"
        "if(!backdrop) return;"
        "if(event && event.target===backdrop) window.toggleExternalLayerDialog(false);"
        "};"
        "window.__applyExternalLayerStyleToDom = function(layer){"
        "if(!layer) return;"
        "var style=window.__extNormalizeStyle(layer.style||{});"
        "layer.style=style;"
        "var cls='.' + window.__extSafeLayerClass(layer.id);"
        "var kind=window.__extGeometryKind(layer);"
        "document.querySelectorAll(cls).forEach(function(el){"
        "try{"
        "var tag=String(el.tagName||'').toLowerCase();"
        "var isPoint=(kind==='point') || tag==='circle';"
        "if(isPoint){"
        "el.style.fill=String(style.color);"
        "el.setAttribute('fill', String(style.color));"
        "el.style.stroke=String(style.color);"
        "el.setAttribute('stroke', String(style.color));"
        "el.style.strokeWidth=String(Math.max(1, style.line_width*0.5));"
        "el.setAttribute('stroke-width', String(Math.max(1, style.line_width*0.5)));"
        "el.style.opacity=String(style.line_opacity);"
        "el.setAttribute('opacity', String(style.line_opacity));"
        "if(tag==='circle'){"
        "el.setAttribute('r', String(style.point_size));"
        "}"
        "}else{"
        "el.style.stroke=String(style.color);"
        "el.setAttribute('stroke', String(style.color));"
        "el.style.strokeWidth=String(style.line_width);"
        "el.setAttribute('stroke-width', String(style.line_width));"
        "el.style.strokeOpacity=String(style.line_opacity);"
        "el.setAttribute('stroke-opacity', String(style.line_opacity));"
        "if(kind==='line'){"
        "el.style.fill='none';"
        "el.setAttribute('fill', 'none');"
        "el.style.fillOpacity='0';"
        "el.setAttribute('fill-opacity', '0');"
        "}else{"
        "el.style.fill=String(style.color);"
        "el.setAttribute('fill', String(style.color));"
        "el.style.fillOpacity=String(style.fill_opacity);"
        "el.setAttribute('fill-opacity', String(style.fill_opacity));"
        "}"
        "}"
        "}catch(err){}"
        "});"
        "if(kind==='point' && window.__applyExternalPointRadiusForLayer){"
        "window.__applyExternalPointRadiusForLayer(layer.id, style.point_size);"
        "}"
        "};"
        "window.__applyExternalPointRadiusForLayer = function(layerId, radius){"
        "try{"
        "var r=Number(radius);"
        "if(!isFinite(r)) return;"
        "r=Math.max(2, Math.min(24, r));"
        "var mm=null;"
        "try{ if(window.findMap) mm=window.findMap(); }catch(err){}"
        "try{ if(!mm && window.map && typeof window.map.eachLayer==='function') mm=window.map; }catch(err){}"
        "if(!mm || typeof mm.eachLayer!=='function') return;"
        "var need=window.__extSafeLayerClass(layerId);"
        "mm.eachLayer(function(layer){"
        "try{"
        "if(!layer || typeof layer.setRadius!=='function') return;"
        "var cls='';"
        "if(layer.options && layer.options.className) cls=String(layer.options.className||'');"
        "if((!cls || cls.indexOf(need)===-1) && layer._path && layer._path.getAttribute) cls=String(layer._path.getAttribute('class')||'');"
        "if(String(cls).indexOf(need)===-1) return;"
        "layer.setRadius(r);"
        "}catch(err){}"
        "});"
        "}catch(err){}"
        "};"
        "window.__applyExternalLayerVisibilityState = function(groupVisible){"
        "var list=Array.isArray(window.__externalLayerCatalog)?window.__externalLayerCatalog:[];"
        "var hasCatalog=list.length>0;"
        "if(hasCatalog){"
        "list.forEach(function(layer){"
        "var cls='.' + window.__extSafeLayerClass(layer.id);"
        "var visible=!!groupVisible && !!layer.visible;"
        "document.querySelectorAll(cls).forEach(function(el){"
        "el.style.display = visible ? '' : 'none';"
        "});"
        "});"
        "}else{"
        "document.querySelectorAll('.overlay-external').forEach(function(el){"
        "el.style.display = groupVisible ? '' : 'none';"
        "});"
        "}"
        "if(window.__updateExternalLayerSummary) window.__updateExternalLayerSummary();"
        "};"
        "window.__renderExternalLayerLegendList = function(){"
        "var listEl=document.getElementById('legendExternalList');"
        "if(!listEl) return;"
        "var list=Array.isArray(window.__externalLayerCatalog)?window.__externalLayerCatalog:[];"
        "listEl.innerHTML='';"
        "if(!list.length) return;"
        "if(!listEl.__extLegendBound){"
        "listEl.__extLegendBound = true;"
        "listEl.addEventListener('dragover', function(e){ if(e && e.preventDefault) e.preventDefault(); });"
        "listEl.addEventListener('drop', function(e){"
        "try{ if(e && e.preventDefault) e.preventDefault(); }catch(err){}"
        "var dragId=String(window.__extLegendDragId||'');"
        "if(!dragId) return;"
        "var listNow=Array.isArray(window.__externalLayerCatalog)?window.__externalLayerCatalog:[];"
        "var display=listNow.slice().reverse().map(function(l){ return String(l.id||''); }).filter(function(v){ return !!v; });"
        "var idx=display.indexOf(dragId);"
        "if(idx===-1) return;"
        "display.splice(idx,1);"
        "display.push(dragId);"
        "if(window.__commitExternalLayerOrder) window.__commitExternalLayerOrder(display);"
        "});"
        "}"
        "var display=list.slice().reverse();"
        "display.forEach(function(layer){"
        "var id=String(layer.id||'');"
        "if(!id) return;"
        "var kind=window.__extGeometryKind(layer);"
        "var style=window.__extNormalizeStyle(layer.style||{});"
        "layer.style=style;"
        "var row=document.createElement('div');"
        "row.className='legend-item legend-external-item' + (layer.visible ? '' : ' is-hidden');"
        "row.setAttribute('data-layer-id', id);"
        "row.addEventListener('dragover', function(e){"
        "if(e && e.preventDefault) e.preventDefault();"
        "try{"
        "var r=row.getBoundingClientRect();"
        "var before=(e.clientY < (r.top + (r.height/2)));"
        "row.setAttribute('data-drop', before ? 'before' : 'after');"
        "row.classList.add('drag-over');"
        "}catch(err){}"
        "});"
        "row.addEventListener('dragleave', function(){ row.classList.remove('drag-over'); row.removeAttribute('data-drop'); });"
        "row.addEventListener('drop', function(e){"
        "try{ if(e && e.preventDefault) e.preventDefault(); }catch(err){}"
        "var dragId=String(window.__extLegendDragId||'');"
        "var targetId=String(row.getAttribute('data-layer-id')||'');"
        "row.classList.remove('drag-over');"
        "var pos=String(row.getAttribute('data-drop')||'before');"
        "row.removeAttribute('data-drop');"
        "if(!dragId || !targetId || dragId===targetId) return;"
        "var displayIds=list.slice().reverse().map(function(l){ return String(l.id||''); }).filter(function(v){ return !!v; });"
        "var from=displayIds.indexOf(dragId);"
        "var to=displayIds.indexOf(targetId);"
        "if(from===-1 || to===-1) return;"
        "displayIds.splice(from,1);"
        "if(from < to) to = to - 1;"
        "if(pos==='after') to = to + 1;"
        "to=Math.max(0, Math.min(displayIds.length, to));"
        "displayIds.splice(to, 0, dragId);"
        "if(window.__commitExternalLayerOrder) window.__commitExternalLayerOrder(displayIds);"
        "});"
        "var handle=document.createElement('span');"
        "handle.className='legend-external-handle';"
        "handle.textContent='::';"
        "handle.setAttribute('title','Drag to reorder');"
        "handle.draggable=true;"
        "handle.addEventListener('dragstart', function(e){"
        "window.__extLegendDragId = id;"
        "try{ if(e && e.dataTransfer) e.dataTransfer.setData('text/plain', id); }catch(err){}"
        "try{ row.classList.add('dragging'); }catch(err){}"
        "});"
        "handle.addEventListener('dragend', function(){"
        "window.__extLegendDragId = null;"
        "try{ row.classList.remove('dragging'); }catch(err){}"
        "});"
        "var sym=document.createElement('div');"
        "sym.className='legend-symbol';"
        "if(kind==='line'){"
        "sym.style.width='18px';"
        "sym.style.height='0';"
        "sym.style.background='transparent';"
        "sym.style.borderRadius='0';"
        "sym.style.borderTop=String(Math.max(1, Math.round(style.line_width))) + 'px solid ' + String(window.__extHexToRgba(style.color, style.line_opacity));"
        "}else if(kind==='polygon' || kind==='mixed'){"
        "sym.classList.add('square');"
        "sym.style.background=String(window.__extHexToRgba(style.color, style.fill_opacity));"
        "sym.style.border=String(Math.max(1, Math.round(style.line_width))) + 'px solid ' + String(window.__extHexToRgba(style.color, style.line_opacity));"
        "}else{"
        "sym.style.background=String(style.color);"
        "sym.style.border='2px solid rgba(255,255,255,0.85)';"
        "sym.style.opacity=String(style.line_opacity);"
        "}"
        "var lbl=document.createElement('span');"
        "lbl.className='legend-label legend-external-label';"
        "lbl.textContent=String(layer.name||'External Layer');"
        "var finishEdit=function(commit){"
        "lbl.removeAttribute('contenteditable');"
        "lbl.blur();"
        "var next=String(lbl.textContent||'').trim();"
        "if(!commit || !next){"
        "lbl.textContent=String(layer.name||'External Layer');"
        "return;"
        "}"
        "if(String(layer.name||'')===next) return;"
        "layer.name = next;"
        "if(window.pyBridge && window.pyBridge.onExternalLayerRenamed){"
        "try{ window.pyBridge.onExternalLayerRenamed(String(layer.id||''), next); }catch(err){}"
        "}"
        "if(window.__updateExternalLayerSummary) window.__updateExternalLayerSummary();"
        "};"
        "lbl.addEventListener('dblclick', function(e){"
        "lbl.setAttribute('data-default-text', String(lbl.textContent||''));"
        "lbl.setAttribute('contenteditable','true');"
        "lbl.focus();"
        "try{ document.execCommand('selectAll', false, null); }catch(err){}"
        "if(e && e.preventDefault) e.preventDefault();"
        "if(e && e.stopPropagation) e.stopPropagation();"
        "});"
        "lbl.addEventListener('keydown', function(e){"
        "if(e && e.key==='Enter'){ finishEdit(true); if(e.preventDefault) e.preventDefault(); }"
        "else if(e && e.key==='Escape'){ finishEdit(false); if(e.preventDefault) e.preventDefault(); }"
        "});"
        "lbl.addEventListener('blur', function(){ finishEdit(true); });"
        "var meta=document.createElement('span');"
        "meta.className='legend-external-meta';"
        "meta.textContent=String(layer.geometry||layer.geometry_kind||kind||'');"
        "row.appendChild(handle);"
        "row.appendChild(sym);"
        "row.appendChild(lbl);"
        "row.appendChild(meta);"
        "listEl.appendChild(row);"
        "});"
        "};"
        "window.__commitExternalLayerOrder = function(displayIds){"
        "try{"
        "var display=Array.isArray(displayIds)?displayIds.slice():[];"
        "display=display.map(function(v){ return String(v||''); }).filter(function(v){ return !!v; });"
        "if(!display.length) return;"
        "var internal=display.slice().reverse();"
        "var list=Array.isArray(window.__externalLayerCatalog)?window.__externalLayerCatalog:[];"
        "var byId={};"
        "list.forEach(function(layer){ byId[String(layer.id||'')] = layer; });"
        "var used={};"
        "var next=[];"
        "internal.forEach(function(id){ if(byId[id]){ next.push(byId[id]); used[id]=true; } });"
        "list.forEach(function(layer){ var id=String(layer.id||''); if(id && !used[id]) next.push(layer); });"
        "window.__externalLayerCatalog = next;"
        "window.__externalLayerOrderSig = internal.join('|');"
        "if(window.__applyExternalLayerZOrder) window.__applyExternalLayerZOrder(internal);"
        "if(window.__updateExternalLayerSummary) window.__updateExternalLayerSummary();"
        "if(window.pyBridge && window.pyBridge.onExternalLayerOrderChanged){"
        "try{ window.pyBridge.onExternalLayerOrderChanged(JSON.stringify(internal)); }catch(err){}"
        "}"
        "}catch(err){}"
        "};"
        "window.__renderExternalLayerList = function(){"
        "var listEl=document.getElementById('externalLayerList');"
        "if(!listEl) return;"
        "var list=Array.isArray(window.__externalLayerCatalog)?window.__externalLayerCatalog:[];"
        "listEl.innerHTML='';"
        "if(!list.length){"
        "var note=document.createElement('div');"
        "note.className='external-layer-empty';"
        "note.textContent='No external layers loaded.';"
        "listEl.appendChild(note);"
        "return;"
        "}"
        "list.forEach(function(layer){"
        "var row=document.createElement('div');"
        "row.className='external-layer-row' + ((String(layer.id||'')===String(window.__selectedExternalLayerId||'')) ? ' active' : '');"
        "row.addEventListener('click', function(){ window.__selectExternalLayer(layer.id); });"
        "var info=document.createElement('div');"
        "var name=document.createElement('div'); name.className='external-layer-row-name'; name.textContent=String(layer.name||'Layer');"
        "var meta=document.createElement('div'); meta.className='external-layer-row-meta';"
        "meta.textContent=String(layer.geometry||layer.geometry_kind||'Unknown') + ' \\u2022 ' + String(layer.feature_count||0) + ' features';"
        "info.appendChild(name); info.appendChild(meta);"
        "var btn=document.createElement('button');"
        "btn.className='external-visibility-btn' + (layer.visible ? ' on' : '');"
        "btn.textContent=layer.visible ? 'Visible' : 'Hidden';"
        "btn.addEventListener('click', function(e){"
        "if(e && e.stopPropagation) e.stopPropagation();"
        "window.__setExternalLayerVisible(layer.id, !layer.visible, true);"
        "});"
        "row.appendChild(info);"
        "row.appendChild(btn);"
        "listEl.appendChild(row);"
        "});"
        "};"
        "window.__syncExternalLayerDetail = function(){"
        "var layer=window.__getSelectedExternalLayer();"
        "var disabled=!layer;"
        "var nameEl=document.getElementById('detailLayerName');"
        "var geomEl=document.getElementById('detailLayerGeometry');"
        "var srcEl=document.getElementById('detailLayerSource');"
        "var featEl=document.getElementById('detailLayerFeatures');"
        "if(nameEl) nameEl.textContent=layer ? String(layer.name||'-') : '-';"
        "if(geomEl) geomEl.textContent=layer ? String(layer.geometry||layer.geometry_kind||'-') : '-';"
        "if(srcEl) srcEl.textContent=layer ? String(layer.source||'-') : '-';"
        "if(featEl) featEl.textContent=layer ? String(layer.feature_count||0) : '-';"
        "var style=window.__extNormalizeStyle(layer ? layer.style : {});"
        "if(layer) layer.style=style;"
        "var colorInput=document.getElementById('extStyleColor');"
        "var lineWidth=document.getElementById('extStyleLineWidth');"
        "var lineOpacity=document.getElementById('extStyleLineOpacity');"
        "var fillOpacity=document.getElementById('extStyleFillOpacity');"
        "var pointSize=document.getElementById('extStylePointSize');"
        "if(colorInput){ colorInput.value=String(style.color||'#22c55e'); colorInput.disabled=disabled; }"
        "if(lineWidth){ lineWidth.value=String(style.line_width); lineWidth.disabled=disabled; }"
        "if(lineOpacity){ lineOpacity.value=String(Math.round(style.line_opacity*100)); lineOpacity.disabled=disabled; }"
        "if(fillOpacity){ fillOpacity.value=String(Math.round(style.fill_opacity*100)); fillOpacity.disabled=disabled; }"
        "if(pointSize){ pointSize.value=String(Math.round(style.point_size)); pointSize.disabled=disabled; }"
        "var lwVal=document.getElementById('extStyleLineWidthValue');"
        "var loVal=document.getElementById('extStyleLineOpacityValue');"
        "var foVal=document.getElementById('extStyleFillOpacityValue');"
        "var psVal=document.getElementById('extStylePointSizeValue');"
        "if(lwVal) lwVal.textContent=String(Math.round(style.line_width)) + ' px';"
        "if(loVal) loVal.textContent=String(Math.round(style.line_opacity*100)) + '%';"
        "if(foVal) foVal.textContent=String(Math.round(style.fill_opacity*100)) + '%';"
        "if(psVal) psVal.textContent=String(Math.round(style.point_size)) + ' px';"
        "var kind=window.__extGeometryKind(layer);"
        "var lineWidthRow=document.getElementById('extStyleLineWidthRow');"
        "var lineOpacityRow=document.getElementById('extStyleLineOpacityRow');"
        "var fillOpacityRow=document.getElementById('extStyleFillOpacityRow');"
        "var pointSizeRow=document.getElementById('extStylePointSizeRow');"
        "if(lineWidthRow) lineWidthRow.style.display=(kind==='line'||kind==='polygon'||kind==='mixed') ? '' : 'none';"
        "if(lineOpacityRow) lineOpacityRow.style.display=(kind==='line'||kind==='polygon'||kind==='point'||kind==='mixed'||kind==='other') ? '' : 'none';"
        "if(fillOpacityRow) fillOpacityRow.style.display=(kind==='polygon'||kind==='mixed') ? '' : 'none';"
        "if(pointSizeRow) pointSizeRow.style.display=(kind==='point'||kind==='mixed') ? '' : 'none';"
        "};"
        "window.__updateExternalLayerSummary = function(){"
        "var list=Array.isArray(window.__externalLayerCatalog)?window.__externalLayerCatalog:[];"
        "var total=list.length;"
        "var visible=list.filter(function(layer){ return !!layer.visible; });"
        "var visibleCount=visible.length;"
        "var summary=String(total) + ' loaded (' + String(visibleCount) + ' visible)';"
        "var countEl=document.getElementById('externalLayerCount');"
        "var propCountEl=document.getElementById('propExternalLayerCount');"
        "var legendCountEl=document.getElementById('legendExternalLabel');"
        "if(countEl) countEl.textContent=summary;"
        "if(propCountEl) propCountEl.textContent=summary;"
        "if(legendCountEl) legendCountEl.textContent=summary;"
        "var selected=window.__getSelectedExternalLayer();"
        "var noteEl=document.getElementById('propExternalLayerNote');"
        "if(noteEl){"
        "if(selected) noteEl.textContent='Active: ' + String(selected.name||'-') + ' (' + String(selected.geometry||selected.geometry_kind||'-') + ')';"
        "else noteEl.textContent='No external layers loaded.';"
        "}"
        "var kinds={};"
        "visible.forEach(function(layer){ kinds[window.__extGeometryKind(layer)] = true; });"
        "var labels=[];"
        "if(kinds.polygon) labels.push('Polygon');"
        "if(kinds.line) labels.push('Line');"
        "if(kinds.point) labels.push('Point');"
        "if(kinds.mixed && labels.length===0) labels.push('Mixed');"
        "if(kinds.other && labels.length===0) labels.push('Geometry');"
        "var geomEl=document.getElementById('legendExternalGeometry');"
        "if(geomEl) geomEl.textContent = labels.length ? labels.join(' / ') : 'No visible geometry';"
        "var sec=document.getElementById('legendSectionExternal');"
        "var state=window.__mapLayerState||{};"
        "var groupVisible=(state.external!==false);"
        "if(sec) sec.style.display=(groupVisible && total>0) ? '' : 'none';"
        "if(window.__renderExternalLayerLegendList) window.__renderExternalLayerLegendList();"
        "};"
        "window.__selectExternalLayer = function(layerId){"
        "window.__selectedExternalLayerId = String(layerId||'');"
        "window.__renderExternalLayerList();"
        "window.__syncExternalLayerDetail();"
        "window.__updateExternalLayerSummary();"
        "};"
        "window.__setExternalLayerVisible = function(layerId, visible, notifyPython){"
        "var list=Array.isArray(window.__externalLayerCatalog)?window.__externalLayerCatalog:[];"
        "var id=String(layerId||'');"
        "var layer=null;"
        "for(var i=0;i<list.length;i++){"
        "if(String(list[i].id||'')===id){ layer=list[i]; break; }"
        "}"
        "if(!layer) return;"
        "layer.visible=!!visible;"
        "window.__renderExternalLayerList();"
        "var state=window.__mapLayerState||{};"
        "window.__applyExternalLayerVisibilityState(state.external!==false);"
        "window.__updateExternalLayerSummary();"
        "if(notifyPython && window.pyBridge && window.pyBridge.onExternalLayerVisibilityChanged){"
        "try{ window.pyBridge.onExternalLayerVisibilityChanged(id, !!visible); }catch(err){}"
        "}"
        "};"
        "window.__scheduleExternalLayerStyleCommit = function(layerId){"
        "var id=String(layerId||'');"
        "if(!id) return;"
        "var timers=window.__externalLayerStyleTimers || {};"
        "if(timers[id]){ try{ clearTimeout(timers[id]); }catch(err){} }"
        "timers[id]=setTimeout(function(){"
        "delete timers[id];"
        "var layer=null;"
        "var list=Array.isArray(window.__externalLayerCatalog)?window.__externalLayerCatalog:[];"
        "for(var i=0;i<list.length;i++){ if(String(list[i].id||'')===id){ layer=list[i]; break; } }"
        "if(!layer) return;"
        "if(window.pyBridge && window.pyBridge.onExternalLayerStyleChanged){"
        "try{ window.pyBridge.onExternalLayerStyleChanged(id, JSON.stringify(layer.style||{})); }catch(err){}"
        "}"
        "}, 180);"
        "window.__externalLayerStyleTimers = timers;"
        "};"
        "window.__onExternalStyleInput = function(field, value){"
        "var layer=window.__getSelectedExternalLayer();"
        "if(!layer) return;"
        "var style=window.__extNormalizeStyle(layer.style||{});"
        "if(field==='color'){ style.color=String(value||style.color); }"
        "else if(field==='line_width'){ style.line_width=Math.max(1, Math.min(8, Number(value)||style.line_width)); }"
        "else if(field==='line_opacity'){ style.line_opacity=Math.max(0.05, Math.min(1, (Number(value)||Math.round(style.line_opacity*100))/100)); }"
        "else if(field==='fill_opacity'){ style.fill_opacity=Math.max(0, Math.min(1, (Number(value)||Math.round(style.fill_opacity*100))/100)); }"
        "else if(field==='point_size'){ style.point_size=Math.max(2, Math.min(24, Number(value)||style.point_size)); }"
        "layer.style=style;"
        "window.__syncExternalLayerDetail();"
        "window.__applyExternalLayerStyleToDom(layer);"
        "window.__scheduleExternalLayerStyleCommit(layer.id);"
        "};"
        "window.__setExternalLayerCatalog = function(catalog){"
        "var oldSelected=String(window.__selectedExternalLayerId||'');"
        "var inList=Array.isArray(catalog)?catalog:[];"
        "window.__externalLayerCatalog = inList.map(function(item){"
        "item=(item&&typeof item==='object')?item:{};"
        "var layer={"
        "id:String(item.id||''),"
        "name:String(item.name||'External Layer'),"
        "geometry:String(item.geometry||item.geometry_kind||'Unknown'),"
        "geometry_kind:String(item.geometry_kind||item.geometry||'other').toLowerCase(),"
        "source:String(item.source||'-'),"
        "feature_count:Number(item.feature_count||0),"
        "visible:(item.visible!==false),"
        "style:window.__extNormalizeStyle(item.style||{})"
        "};"
        "return layer;"
        "});"
        "if(!window.__externalLayerCatalog.length){"
        "window.__selectedExternalLayerId = null;"
        "}else{"
        "var found=false;"
        "for(var i=0;i<window.__externalLayerCatalog.length;i++){"
        "if(String(window.__externalLayerCatalog[i].id||'')===oldSelected){ found=true; break; }"
        "}"
        "window.__selectedExternalLayerId = found ? oldSelected : String(window.__externalLayerCatalog[0].id||'');"
        "}"
        "window.__renderExternalLayerList();"
        "window.__syncExternalLayerDetail();"
        "window.__externalLayerCatalog.forEach(function(layer){ window.__applyExternalLayerStyleToDom(layer); });"
        "var state=window.__mapLayerState||{};"
        "window.__applyExternalLayerVisibilityState(state.external!==false);"
        "var sig=window.__externalLayerCatalog.map(function(l){ return String(l.id||''); }).join('|');"
        "if(sig !== String(window.__externalLayerOrderSig||'')){"
        "window.__externalLayerOrderSig = sig;"
        "if(window.__applyExternalLayerZOrder) window.__applyExternalLayerZOrder(window.__externalLayerCatalog.map(function(l){ return String(l.id||''); }));"
        "}"
        "window.__updateExternalLayerSummary();"
        "setTimeout(function(){ try{ if(window.__bindExternalLayerPopups) window.__bindExternalLayerPopups(); }catch(err){} }, 0);"
        "};"
        "window.__applyExternalLayerStyleFromPython = function(layerId, style){"
        "var list=Array.isArray(window.__externalLayerCatalog)?window.__externalLayerCatalog:[];"
        "var id=String(layerId||'');"
        "for(var i=0;i<list.length;i++){"
        "if(String(list[i].id||'')===id){"
        "list[i].style=window.__extNormalizeStyle(style||{});"
        "window.__applyExternalLayerStyleToDom(list[i]);"
        "break;"
        "}"
        "}"
        "window.__syncExternalLayerDetail();"
        "};"
        "window.__initExternalLayerUi = function(){"
        "if(window.__externalLayerUiInit) return;"
        "window.__externalLayerUiInit = true;"
        "if(!window.__externalLayerEscBound){"
        "window.__externalLayerEscBound = true;"
        "document.addEventListener('keydown', function(e){"
        "if(!e) return;"
        "if(e.key==='Escape'){"
        "var backdrop=document.getElementById('layerManagerBackdrop');"
        "if(backdrop && backdrop.classList.contains('open')) window.toggleExternalLayerDialog(false);"
        "}"
        "});"
        "}"
        "if(window.__setExternalLayerCatalog) window.__setExternalLayerCatalog(window.__externalLayerCatalog||[]);"
        "};"
        "if(document.readyState==='loading'){"
        "document.addEventListener('DOMContentLoaded', function(){"
        "if(window.__initExternalLayerUi) window.__initExternalLayerUi();"
        "});"
        "}else{"
        "setTimeout(function(){ if(window.__initExternalLayerUi) window.__initExternalLayerUi(); }, 0);"
        "}"
    )
