"""Heatmap runtime JS helpers for MapWidget."""


def build_replace_dynamic_heatmap_js() -> str:
    """Return JS that replaces heatmap visuals without full HTML reload."""
    return (
        "window.__replaceDynamicHeatmap = function(payload){"
        "try{"
        "if(!window.L) return;"
        "var m = (typeof findMap === 'function') ? findMap() : null;"
        "if(!m) return;"
        "if(!window.__dynHeatmap){ window.__dynHeatmap = L.layerGroup(); }"
        "if(window.__dynHeatmap){ try{ m.removeLayer(window.__dynHeatmap); }catch(err){} }"
        "if(m && m.eachLayer){"
        "m.eachLayer(function(layer){"
        "try{"
        "if(!layer) return;"
        "var cls = String((layer.options && layer.options.className) || '');"
        "if(cls.indexOf('dynamic-heatmap') !== -1){ m.removeLayer(layer); return; }"
        "if(layer._canvas && layer._canvas.classList && layer._canvas.classList.contains('leaflet-heatmap-layer')){"
        "m.removeLayer(layer);"
        "}"
        "}catch(err){}"
        "});"
        "}"
        "window.__dynHeatmap = L.layerGroup();"
        "var pts = (payload && payload.points) ? payload.points : [];"
        "pts.forEach(function(p){"
        "try{"
        "var w = Number(p.w || 0);"
        "if(!isFinite(w)) w = 0;"
        "w = Math.max(0, Math.min(1, w));"
        "var color = (w < 0.34) ? '#4ade80' : ((w < 0.67) ? '#fbbf24' : '#f87171');"
        "var radius = 5 + (12 * w);"
        "L.circleMarker([Number(p.lat), Number(p.lon)], {"
        "radius: radius, color: color, weight: 1, opacity: 0.75,"
        "fill: true, fillColor: color, fillOpacity: Number(p.opacity || 0.5),"
        "className: 'leaflet-heatmap-layer dynamic-heatmap'"
        "}).addTo(window.__dynHeatmap);"
        "}catch(err){}"
        "});"
        "window.__dynHeatmap.addTo(m);"
        "if(window.__lastOverlayState && window.__applyOverlayVisibility){ window.__applyOverlayVisibility(window.__lastOverlayState); }"
        "}catch(err){}"
        "};"
    )

