"""Layer-panel and overlay-visibility runtime JS helpers for MapWidget."""


def build_layers_runtime_js() -> str:
    """Return shared JS contract for layer panel state + overlay visibility."""
    return (
        "window.__applyLayerPanelState = function(state){"
        "if(!state) return;"
        "var items=document.querySelectorAll('.map-layers-panel .layer-item');"
        "items.forEach(function(item){"
        "try{"
        "var onclickText=item.getAttribute('onclick')||'';"
        "var m=onclickText.match(/toggleLayer\\('([^']+)'/);"
        "if(!m) return;"
        "var name=m[1];"
        "if(Object.prototype.hasOwnProperty.call(state,name)){"
        "item.classList.toggle('active', !!state[name]);"
        "}"
        "}catch(err){}"
        "});"
        "};"
        "window.__normalizeLayerState = function(state){"
        "var prev = window.__mapLayerState || {};"
        "return {"
        "points: (state && state.points!==undefined) ? !!state.points : !!prev.points,"
        "excluded: (state && state.excluded!==undefined) ? !!state.excluded : !!prev.excluded,"
        "external: (state && state.external!==undefined) ? !!state.external : !!prev.external,"
        "heatmap: (state && state.heatmap!==undefined) ? !!state.heatmap : !!prev.heatmap,"
        "coverage: (state && state.coverage!==undefined) ? !!state.coverage : !!prev.coverage,"
        "vectors: (state && state.vectors!==undefined) ? !!state.vectors : !!prev.vectors,"
        "main_arrow: (state && state.main_arrow!==undefined) ? !!state.main_arrow : !!prev.main_arrow,"
        "contours: (state && state.contours!==undefined) ? !!state.contours : !!prev.contours,"
        "transect: (state && state.transect!==undefined) ? !!state.transect : !!prev.transect"
        "};"
        "};"
        "window.__applyOverlayVisibility = function(state){"
        "if(!state) return;"
        "window.__lastOverlayState = state;"
        "var setDisplay=function(sel, visible){"
        "document.querySelectorAll(sel).forEach(function(el){"
        "el.style.display = visible ? '' : 'none';"
        "});"
        "};"
        "var hasDynContours = !!(window.__dynContour && (window.__dynContour.line || window.__dynContour.fill || window.__dynContour.label));"
        "if(window.__applyExternalLayerVisibilityState){"
        "window.__applyExternalLayerVisibilityState(!!state.external);"
        "}else{"
        "setDisplay('.overlay-external', !!state.external);"
        "}"
        "setDisplay('.leaflet-heatmap-layer', !!state.heatmap);"
        "setDisplay('.overlay-coverage', !!state.coverage);"
        "setDisplay(hasDynContours ? '.dynamic-contour' : '.overlay-contours', !!state.contours);"
        "setDisplay(hasDynContours ? '.dynamic-contour-fill' : '.overlay-contours-fill', !!state.contours);"
        "setDisplay(hasDynContours ? '.dynamic-contour-label' : '.contour-line-label', !!state.contours);"
        "if(hasDynContours){"
        "setDisplay('.overlay-contours:not(.dynamic-contour)', false);"
        "setDisplay('.overlay-contours-fill:not(.dynamic-contour-fill)', false);"
        "setDisplay('.contour-line-label:not(.dynamic-contour-label)', false);"
        "}"
        "setDisplay('.overlay-vectors', !!state.vectors);"
        "setDisplay('.overlay-main-arrow', !!state.main_arrow);"
        "if(window.__setContourLayersVisible) window.__setContourLayersVisible(!!state.contours);"
        "if(window.__updateExternalLayerSummary) window.__updateExternalLayerSummary();"
        "if(window.__applyLegendState) window.__applyLegendState(state);"
        "if(window.__haSetTransectEnabled) window.__haSetTransectEnabled(!!state.transect);"
        "};"
        "window.__setMapLayerState = function(state){"
        "var next = window.__normalizeLayerState ? window.__normalizeLayerState(state) : state;"
        "window.__mapLayerState = next;"
        "if(window.__applyLayerPanelState) window.__applyLayerPanelState(next);"
        "if(window.__applyOverlayVisibility) window.__applyOverlayVisibility(next);"
        "if(window.__applyLegendState) window.__applyLegendState(next);"
        "};"
    )
