"""Legend runtime JS helpers for MapWidget."""


def build_legend_runtime_js() -> str:
    """Return JS for point/contour legend rendering and visibility state."""
    return (
        "window.__applyPointLegend = function(cfg){"
        "var row=document.getElementById('legendPointValueScale');"
        "var grad=document.getElementById('legendPointValueGradient');"
        "var min=document.getElementById('legendPointValueMin');"
        "var max=document.getElementById('legendPointValueMax');"
        "if(!row) return;"
        "var enabled=!!(cfg && cfg.enabled);"
        "row.style.display = enabled ? 'flex' : 'none';"
        "if(!enabled) return;"
        "if(grad && cfg.gradient) grad.style.background = String(cfg.gradient);"
        "if(min) min.textContent = String((cfg.min_label!==undefined&&cfg.min_label!==null)?cfg.min_label:'-');"
        "if(max) max.textContent = String((cfg.max_label!==undefined&&cfg.max_label!==null)?cfg.max_label:'-');"
        "};"
        "window.__applyLegendState = function(state){"
        "if(!state) return;"
        "var panel=document.querySelector('.map-legend');"
        "var secPoints=document.getElementById('legendSectionPoints');"
        "var secHeat=document.getElementById('legendSectionHeatmap');"
        "var secContours=document.getElementById('legendSectionContours');"
        "var secCoverage=document.getElementById('legendSectionCoverage');"
        "var secVectors=document.getElementById('legendSectionVectors');"
        "var secExternal=document.getElementById('legendSectionExternal');"
        "var itemActive=document.getElementById('legendItemActivePoint');"
        "var itemExcluded=document.getElementById('legendItemExcludedPoint');"
        "var showPoints=!!state.points || !!state.excluded;"
        "var hasExternal=!!(window.__externalLayerCatalog && window.__externalLayerCatalog.length);"
        "var showExternal=!!state.external && hasExternal;"
        "var showHeat=!!state.heatmap;"
        "var showContours=!!state.contours;"
        "var showCoverage=!!state.coverage;"
        "var showVectors=!!state.vectors;"
        "var showMainArrow=!!state.main_arrow;"
        "if(secPoints) secPoints.style.display = showPoints ? '' : 'none';"
        "if(secExternal) secExternal.style.display = showExternal ? '' : 'none';"
        "if(secHeat) secHeat.style.display = showHeat ? '' : 'none';"
        "if(secContours) secContours.style.display = showContours ? '' : 'none';"
        "if(secCoverage) secCoverage.style.display = showCoverage ? '' : 'none';"
        "if(secVectors) secVectors.style.display = (showVectors || showMainArrow) ? '' : 'none';"
        "if(itemActive) itemActive.style.display = !!state.points ? '' : 'none';"
        "if(itemExcluded) itemExcluded.style.display = !!state.excluded ? '' : 'none';"
        "var itemMainArrow=document.getElementById('legendItemMainArrow');"
        "if(itemMainArrow) itemMainArrow.style.display = showMainArrow ? '' : 'none';"
        "var pointLegendVisible = false;"
        "if(window.__applyPointLegend && window.__mapPointLegend){"
        "var p=window.__mapPointLegend;"
        "pointLegendVisible = (!!p.available) && !!window.__pointColorByValue && !!state.points;"
        "window.__applyPointLegend({enabled: pointLegendVisible, gradient:p.gradient, min_label:p.min_label, max_label:p.max_label});"
        "}"
        "if(window.__applyContourLegend && window.__mapContourLegend){"
        "var c=window.__mapContourLegend;"
        "window.__applyContourLegend({enabled:(!!c.enabled) && !pointLegendVisible, gradient:c.gradient, min_label:c.min_label, max_label:c.max_label});"
        "}"
        "if(window.__updateExternalLayerSummary) window.__updateExternalLayerSummary();"
        "if(panel) panel.style.display = (showPoints || showExternal || showHeat || showContours || showCoverage || showVectors || showMainArrow) ? '' : 'none';"
        "};"
        "window.__applyContourLegend = function(cfg){"
        "var row=document.getElementById('legendContourFill');"
        "var grad=document.getElementById('legendContourGradient');"
        "var min=document.getElementById('legendContourMin');"
        "var max=document.getElementById('legendContourMax');"
        "if(!row) return;"
        "var enabled=!!(cfg && cfg.enabled);"
        "row.style.display = enabled ? 'flex' : 'none';"
        "if(!enabled) return;"
        "if(grad && cfg.gradient) grad.style.background = String(cfg.gradient);"
        "if(min) min.textContent = String((cfg.min_label!==undefined&&cfg.min_label!==null)?cfg.min_label:'-');"
        "if(max) max.textContent = String((cfg.max_label!==undefined&&cfg.max_label!==null)?cfg.max_label:'-');"
        "};"
    )
