"""Point-layer indexing and event binding runtime JS helpers for MapWidget."""


def build_points_runtime_js() -> str:
    """Return JS contract for point-layer indexing and delegated events."""
    return (
        "window.__haPointLayerByIdx = {};"
        "window.__haCoordToIdx = {};"
        "window.__haCoordKey = function(lat, lon){ return Number(lat).toFixed(7) + '|' + Number(lon).toFixed(7); };"
        "window.__haBuildCoordIndex = function(){"
        "window.__haCoordToIdx = {};"
        "var pm = window.__mapPointData || {};"
        "Object.keys(pm).forEach(function(idx){"
        "var d = pm[idx] || {};"
        "var key = window.__haCoordKey(d.lat, d.lon);"
        "window.__haCoordToIdx[key] = String(idx);"
        "});"
        "};"
        "window.__haIndexPointLayers = function(){"
        "try{"
        "if(window.__haBuildCoordIndex) window.__haBuildCoordIndex();"
        "window.__haPointLayerByIdx = {};"
        "var m = (typeof findMap === 'function') ? findMap() : null;"
        "if(!m || !m.eachLayer) return;"
        "m.eachLayer(function(layer){"
        "try{"
        "if(!layer || typeof layer.getLatLng !== 'function' || typeof layer.setRadius !== 'function') return;"
        "var ll = layer.getLatLng();"
        "if(!ll) return;"
        "var key = window.__haCoordKey(ll.lat, ll.lng);"
        "var idx = window.__haCoordToIdx[key];"
        "if(idx===undefined || idx===null) return;"
        "idx = String(idx);"
        "layer.__haPointIdx = idx;"
        "window.__haPointLayerByIdx[idx] = layer;"
        "var d = (window.__mapPointData || {})[idx] || null;"
        "if(layer._path && layer._path.classList){"
        "layer._path.classList.add('point-marker');"
        "layer._path.classList.add('point-idx-' + idx);"
        "if(d && String(d.status||'').toLowerCase()==='excluded'){"
        "layer._path.classList.add('excluded');"
        "layer._path.classList.remove('active');"
        "} else {"
        "layer._path.classList.add('active');"
        "layer._path.classList.remove('excluded');"
        "}"
        "}"
        "}catch(err){}"
        "});"
        "}catch(err){}"
        "};"
        "window.__haForEachPointLayer = function(fn){"
        "if(!fn) return;"
        "if(window.__haIndexPointLayers) window.__haIndexPointLayers();"
        "var map = window.__haPointLayerByIdx || {};"
        "Object.keys(map).forEach(function(idx){"
        "try{ fn(String(idx), map[idx]); }catch(err){}"
        "});"
        "};"
        "window.__haBindPointLayerEvents = function(){"
        "if(window.__haForEachPointLayer) window.__haForEachPointLayer(function(idx, layer){"
        "if(!layer || layer.__haEventsBound) return;"
        "layer.__haEventsBound = true;"
        "layer.on('click', function(){"
        "var d=(window.__mapPointData||{})[idx]; if(!d) return;"
        "if(window.pyBridge){"
        "window.pyBridge.onPointClick(JSON.stringify({id:String(d.id||''),idx:String(d.idx||idx),member_key:(d.member_key===undefined||d.member_key===null)?'':String(d.member_key)}));"
        "}"
        "if(window.updateSelectionPanel) window.updateSelectionPanel(d);"
        "});"
        "layer.on('mouseover', function(){"
        "var d=(window.__mapPointData||{})[idx]; if(!d) return;"
        "if(window.showTooltip) window.showTooltip(d);"
        "if(window.pyBridge) window.pyBridge.onPointHover(String(d.id||''));"
        "});"
        "layer.on('mouseout', function(){ if(window.hideTooltip) window.hideTooltip(); });"
        "layer.on('mousemove', function(e){"
        "if(window.moveTooltip && e && e.originalEvent) window.moveTooltip(e.originalEvent);"
        "});"
        "});"
        "};"
    )

