"""Transect (polyline) runtime JS helpers for MapWidget."""


def build_transect_lines_js() -> str:
    """
    Return JS that manages multiple persistent transect lines on the map.
    This is separate from the drawing functionality - these are the finalized lines.
    """
    return (
        "window.__haTransectLines = window.__haTransectLines || {"
        "layer:null"
        "};"
        "window.__ensureTransectLinesLayer = function(){"
        "try{"
        "if(!window.findMap){return null;}"
        "if(!window.map){window.findMap();}"
        "var m = window.map || null;"
        "if(!m || !window.L){return null;}"
        "var st = window.__haTransectLines;"
        "if(!st.layer){"
        "st.layer = window.L.layerGroup();"
        "st.layer.addTo(m);"
        "}"
        "return st.layer;"
        "}catch(err){return null;}"
        "};"
        "window.__drawTransectLines = function(lines){"
        "try{"
        "var layer = window.__ensureTransectLinesLayer();"
        "if(!layer) return;"
        "if(layer.clearLayers) layer.clearLayers();"
        "if(!lines || !Array.isArray(lines)) return;"
        "lines.forEach(function(line){"
        "if(!line || !line.coords || line.coords.length < 2) return;"
        "var pts = line.coords;"
        "var color = line.color || '#f472b6';"
        "var isActive = !!line.active;"
        "var weight = isActive ? 4 : 3;"
        "var opacity = isActive ? 1.0 : 0.7;"
        "window.L.polyline(pts, {color:color, weight:weight, opacity:opacity}).addTo(layer);"
        "var letters = ['A','B','C','D','E','F','G','H','I','J'];"
        "var idx = lines.indexOf(line);"
        "var startLetter = letters[idx % letters.length];"
        "var endLetter = startLetter + \"'\";"
        "var mkMarker = function(lat, lon, label){"
        "var cm = window.L.circleMarker([lat, lon], {radius:isActive?7:5, color:color, weight:2, fillColor:color, fillOpacity:1.0});"
        "cm.addTo(layer);"
        "if(label){"
        "try{ cm.bindTooltip(String(label), {permanent:true, direction:'right', className:'transect-label'}); }catch(err){}"
        "}"
        "};"
        "mkMarker(pts[0][0], pts[0][1], startLetter);"
        "mkMarker(pts[pts.length-1][0], pts[pts.length-1][1], endLetter);"
        "});"
        "}catch(err){}"
        "};"
    )


def build_transect_runtime_js() -> str:
    """
    Return JS that implements a lightweight polyline transect tool:
    - Enable: click to add vertices; mouse move shows a preview segment.
    - Finish: double-click or right-click (contextmenu) to finish and emit coords to Python.
    - Reset: after finishing, the next click starts a new transect.
    - Disable: hides transect layer and stops intercepting map clicks.

    Coordinates emitted are a JSON string of [[lat, lon], ...] pairs.
    """
    return (
        "window.__haTransect = window.__haTransect || {"
        "enabled:false,"
        "stage:0,"  # 0: idle, 1: drawing, 2: finished
        "points:[],"
        "preview:null,"
        "layer:null,"
        "bound:false,"
        "kbd:false,"
        "dblZoomWas:null"
        "};"
        "window.__haEnsureTransectLayer = function(){"
        "try{"
        "if(!window.findMap){return null;}"
        "if(!window.map){window.findMap();}"
        "var m = window.map || null;"
        "if(!m || !window.L){return null;}"
        "var st = window.__haTransect;"
        "if(!st.layer){"
        "st.layer = window.L.layerGroup();"
        "st.layer.addTo(m);"
        "}"
        "return st.layer;"
        "}catch(err){return null;}"
        "};"
        "window.__haClearTransect = function(){"
        "try{"
        "var st = window.__haTransect;"
        "if(st.layer && st.layer.clearLayers) st.layer.clearLayers();"
        "st.points=[];"
        "st.preview=null;"
        "st.stage=0;"
        "}catch(err){}"
        "};"
        "window.__haFinishTransect = function(){"
        "try{"
        "var st = window.__haTransect;"
        "if(!st.enabled) return;"
        "if(!st.points || st.points.length<2) return;"
        "st.stage=2;"
        "st.preview=null;"
        "window.__haRenderTransect();"
        "if(window.pyBridge && window.pyBridge.onTransectDrawn){"
        "try{ window.pyBridge.onTransectDrawn(JSON.stringify(st.points)); }catch(err){}"
        "}"
        "}catch(err){}"
        "};"
        "window.__haRenderTransect = function(){"
        "try{"
        "var st = window.__haTransect;"
        "var layer = window.__haEnsureTransectLayer();"
        "if(!layer) return;"
        "if(layer.clearLayers) layer.clearLayers();"
        "if(!st.points || st.points.length===0) return;"
        "var pts = st.points;"
        "var color = '#f472b6';"
        "var mk = function(lat, lon, label){"
        "var cm = window.L.circleMarker([lat, lon], {radius:6, color:color, weight:2, fillColor:color, fillOpacity:1.0});"
        "cm.addTo(layer);"
        "if (label) {"
        "try{ cm.bindTooltip(String(label), {permanent:true, direction:'right', className:'transect-label'}); }catch(err){}"
        "}"
        "};"
        "mk(pts[0][0], pts[0][1], 'A');"
        "if(pts.length>=2){"
        "mk(pts[pts.length-1][0], pts[pts.length-1][1], 'B');"
        "window.L.polyline(pts, {color:color, weight:3, opacity:0.95}).addTo(layer);"
        "}"
        "if(st.stage===1 && st.preview){"
        "window.L.polyline([pts[pts.length-1], st.preview], {color:color, weight:3, opacity:0.60, dashArray:'6,6'}).addTo(layer);"
        "}"
        "}catch(err){}"
        "};"
        "window.__haTransectHitMarker = function(evt){"
        "try{"
        "var t = evt && evt.originalEvent ? evt.originalEvent.target : null;"
        "if(!t) return false;"
        "var cls='';"
        "if(typeof t.className==='string') cls=t.className;"
        "else if(t.className && typeof t.className.baseVal==='string') cls=t.className.baseVal;"
        "else if(t.getAttribute) cls=t.getAttribute('class')||'';"
        "return String(cls).indexOf('point-marker')!==-1;"
        "}catch(err){return false;}"
        "};"
        "window.__haOnTransectMapClick = function(evt){"
        "try{"
        "var st = window.__haTransect;"
        "if(!st.enabled) return;"
        "if(!evt || !evt.latlng) return;"
        "if(window.__haTransectHitMarker(evt)) return;"  # keep point clicks working
        "var lat = Number(evt.latlng.lat);"
        "var lon = Number(evt.latlng.lng);"
        "if(!isFinite(lat) || !isFinite(lon)) return;"
        "if(st.stage===2){"
        "window.__haClearTransect();"
        "}"
        "if(st.stage===0){"
        "window.__haClearTransect();"
        "st.stage=1;"
        "}"
        "if(st.stage===1){"
        "st.points.push([lat, lon]);"
        "st.preview=null;"
        "window.__haRenderTransect();"
        "return;"
        "}"
        "}catch(err){}"
        "};"
        "window.__haOnTransectDblClick = function(evt){"
        "try{"
        "var st = window.__haTransect;"
        "if(!st.enabled) return;"
        "if(evt && evt.originalEvent){"
        "try{ evt.originalEvent.preventDefault(); }catch(err){}"
        "try{ evt.originalEvent.stopPropagation(); }catch(err){}"
        "}"
        "window.__haFinishTransect();"
        "}catch(err){}"
        "};"
        "window.__haOnTransectContextMenu = function(evt){"
        "try{"
        "var st = window.__haTransect;"
        "if(!st.enabled) return;"
        "if(evt && evt.originalEvent){"
        "try{ evt.originalEvent.preventDefault(); }catch(err){}"
        "try{ evt.originalEvent.stopPropagation(); }catch(err){}"
        "}"
        "window.__haFinishTransect();"
        "}catch(err){}"
        "};"
        "window.__haOnTransectMouseMove = function(evt){"
        "try{"
        "var st = window.__haTransect;"
        "if(!st.enabled) return;"
        "if(st.stage!==1) return;"
        "if(!evt || !evt.latlng) return;"
        "var lat = Number(evt.latlng.lat);"
        "var lon = Number(evt.latlng.lng);"
        "if(!isFinite(lat) || !isFinite(lon)) return;"
        "st.preview=[lat, lon];"
        "window.__haRenderTransect();"
        "}catch(err){}"
        "};"
        "window.__haOnTransectKeyDown = function(evt){"
        "try{"
        "var st = window.__haTransect;"
        "if(!st.enabled) return;"
        "var k = evt && (evt.key || evt.code) ? String(evt.key || evt.code) : '';"
        "if(k==='Escape'){"
        "window.__haClearTransect();"
        "st.stage=0;"
        "window.__haRenderTransect();"
        "return;"
        "}"
        "if(k==='Enter'){"
        "window.__haFinishTransect();"
        "return;"
        "}"
        "}catch(err){}"
        "};"
        "window.__haSetTransectEnabled = function(enabled){"
        "try{"
        "if(!window.findMap){return;}"
        "if(!window.map){window.findMap();}"
        "var m = window.map || null;"
        "if(!m) return;"
        "var st = window.__haTransect;"
        "st.enabled = !!enabled;"
        "var cont = (m.getContainer && m.getContainer()) ? m.getContainer() : null;"
        "if(st.enabled){"
        "try{"
        "if(st.dblZoomWas===null && m.doubleClickZoom && typeof m.doubleClickZoom.enabled==='function'){"
        "st.dblZoomWas = !!m.doubleClickZoom.enabled();"
        "}"
        "if(m.doubleClickZoom && m.doubleClickZoom.disable) m.doubleClickZoom.disable();"
        "}catch(err){}"
        "window.__haEnsureTransectLayer();"
        "try{ if(st.layer && m.addLayer) m.addLayer(st.layer); }catch(err){}"
        "if(cont) cont.style.cursor='crosshair';"
        "if(!st.bound){"
        "m.on('click', window.__haOnTransectMapClick);"
        "m.on('dblclick', window.__haOnTransectDblClick);"
        "m.on('contextmenu', window.__haOnTransectContextMenu);"
        "m.on('mousemove', window.__haOnTransectMouseMove);"
        "st.bound=true;"
        "}"
        "if(!st.kbd){"
        "try{ document.addEventListener('keydown', window.__haOnTransectKeyDown); st.kbd=true; }catch(err){}"
        "}"
        "window.__haRenderTransect();"
        "} else {"
        "if(cont) cont.style.cursor='';"
        "if(st.bound){"
        "m.off('click', window.__haOnTransectMapClick);"
        "m.off('dblclick', window.__haOnTransectDblClick);"
        "m.off('contextmenu', window.__haOnTransectContextMenu);"
        "m.off('mousemove', window.__haOnTransectMouseMove);"
        "st.bound=false;"
        "}"
        "if(st.kbd){"
        "try{ document.removeEventListener('keydown', window.__haOnTransectKeyDown); }catch(err){}"
        "st.kbd=false;"
        "}"
        "try{"
        "if(st.dblZoomWas!==null && st.dblZoomWas===true && m.doubleClickZoom && m.doubleClickZoom.enable) m.doubleClickZoom.enable();"
        "}catch(err){}"
        "try{ if(st.layer && m.removeLayer) m.removeLayer(st.layer); }catch(err){}"
        "}"
        "}catch(err){}"
        "};"
    )
