"""Triangle-selection overlay runtime JS helpers for MapWidget."""


def build_replace_triangle_overlay_js() -> str:
    """Return JS that replaces selected-triangle overlay in-place."""
    return (
        "window.__replaceTriangleSelectionOverlay = function(payload){"
        "try{"
        "if(!window.L) return;"
        "var m = (typeof findMap === 'function') ? findMap() : null;"
        "if(!m) return;"
        "if(window.__dynTriangleOverlay){ try{ m.removeLayer(window.__dynTriangleOverlay); }catch(err){} }"
        "if(m && m.eachLayer){"
        "m.eachLayer(function(layer){"
        "try{"
        "if(!layer) return;"
        "var optCls = String((layer.options && layer.options.className) || '');"
        "var pathCls = '';"
        "try{ pathCls = String((layer._path && layer._path.getAttribute) ? (layer._path.getAttribute('class') || '') : ''); }catch(err){}"
        "var cls = (optCls + ' ' + pathCls).trim();"
        "if(!cls) return;"
        "if(cls.indexOf('triangle-selection-overlay') !== -1){ m.removeLayer(layer); }"
        "}catch(err){}"
        "});"
        "}"
        "window.__dynTriangleOverlay = L.layerGroup();"
        "var tris = (payload && payload.triangles) ? payload.triangles : [];"
        "tris.forEach(function(t){"
        "try{"
        "var status = String(t.status || 'kept').toLowerCase();"
        "var color = (status === 'rejected') ? '#f87171' : '#60a5fa';"
        "L.polygon(t.latlngs || [], {"
        "color: color, weight: 2, opacity: 0.95,"
        "fill: true, fillColor: color, fillOpacity: 0.22,"
        "className: 'triangle-selection-overlay'"
        "}).addTo(window.__dynTriangleOverlay);"
        "}catch(err){}"
        "});"
        "window.__dynTriangleOverlay.addTo(m);"
        "if(window.__lastOverlayState && window.__applyOverlayVisibility){ window.__applyOverlayVisibility(window.__lastOverlayState); }"
        "}catch(err){}"
        "};"
    )

